simple_model:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    base_to_proximal_link_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_1
        pid: {p: 0.01, i: 0.0, d: 0.1}

    base_to_proximal_link_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_2
        pid: {p: 0.01, i: 0.0, d: 0.1}

    base_to_proximal_link_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_3
        pid: {p: 0.01, i: 0.0, d: 0.1}

    base_to_proximal_link_4_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_4
        pid: {p: 0.01, i: 0.0, d: 0.1}

    base_to_proximal_link_5_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_5
        pid: {p: 0.01, i: 0.0, d: 0.1}

    base_to_proximal_link_6_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_to_proximal_link_6
        pid: {p: 0.01, i: 0.0, d: 0.1}